# Site settings
title: CleanLi的博客
header-img: img/home-bg.jpg
email: clean_li@yahoo.com
copyright_name: Clean Li
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/cleanhome"
url: "http://cleanhome.com"
github_username:  cleanli

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 12
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# path
categories_path: categories.html
tags_path: tags.html
permalink: /posts/:month-:day-:year/:title.html


#### Widgets
widgets:
- category
- tag
- archive
## provide seven widgets:category,tag,rss,archive,tagcloud,links,weibo,douban

gems: [jekyll-paginate, jekyll-feed]
