# Site settings
title: Clean's Home
header-img: img/home-bg.jpg
email: clean_li@yahoo.com
copyright_name: Clean Li
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/cleanhome"
url: "http://cleanhome.com"
github_username:  cleanli

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: date
paginate: 48
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
