# Site settings
title: CleanLi的博客
header-img: img/home-bg.jpg
email_username: clean_li@yahoo.com
copyright_name: Clean Li
blog_owner: CleanLi（黎涛）
description: "黎涛的博客"
baseurl: "/cleanhome"
url: "http://cleanli.github.io"
github_username: cleanli
totop: true
barcode: img/cleanli.png

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 18
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# path
categories_path: categories.html
tags_path: tags.html
archives_path: archives.html
permalink: /posts/:year-:month-:day/:title.html

links:
  Clean的收藏: https://longhistory.github.io/clean_collecting/index.html
  Jekyll中文: http://jekyllrb.com
  Liquid中文文档: https://liquid.bootcss.com
  Android XRef: http://androidxref.com
  W3school: http://www.w3school.com.cn/index.html

#### Widgets
widgets:
- ab
- category
- tag
- archive
- links
- barcode
## provide seven widgets:category,tag,rss,archive,tagcloud,links,weibo,douban

gems: [jekyll-paginate, jekyll-feed]
